title: brynts here
description: null
permalink: ':title/'
baseurl: ""
url: "https://brynts.github.io"
site-twitter: "https://x.com/brynts"

# Author Settings
author: brynts
author-img: brynts.jpg
about-author: null
social-twitter: brynts
social-facebook: ""
social-github: brynts
social-linkedin: ""
social-email: ""

# Disqus
discus-identifier: brynts

# Tracker
analytics: ""

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
